### ISSUE TITLE
how to heroku

### ISSUE THREAD

**Issue by JaxGamez** [paradoxmoe/RandomMOE#1]
i dont know what to change in the server.js to make it work in heroku

**Comment by verysimplyms** [comment]
Comment out where it attempts to get/use the SSL Keys and encrypt the connection. (Heroku already does this and it causes conflicts when you don't.)

`var options = {
    key: fs.readFileSync(process.env.SSL_KEY),
    cert: fs.readFileSync(process.env.SSL_CERT),
    ca: fs.readFileSync(process.env.SSL_CA)
    }
var server = https.createServer(options, app);
`

`var port = process.env.PORT_SECURE || 443;`

`server.listen(port);`

`console.log("Server is listening on port(s): " + portUnsecure, port);`

All these lines need to be either commented out or modified (mainly commented out and it will all work.)

However I haven't updated this project in an extremely long time so I also don't know if any of the 3rd party libraries used are deprecated. I might reupdate this project eventually but even with the changes it might still be broken. This is what an older version of this repository looked like when on herokuapp: https://vaporwaveom.herokuapp.com/

**Comment by verysimplyms** [comment]
This is what an older version of this repository looked like when on herokuapp: https://vaporwaveom.herokuapp.com/
